# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: joseycdev
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: aws-node-s3
# "service" is the name of this project. This will also be added to your AWS resource names.
service: aws-node-s3

useDotenv: true

provider:
  name: aws
  runtime: nodejs20.x
  stage: dev 
  region: us-east-1
  logs:
    restApi: true
  apiGateway:
    shouldStartNameWithService: true
  environment:
    REGION: ${self:provider.region}
    BUCKET: bucket-serverless-github-challenge
    SECRET_JWT: ${ssm/SECRET_JWT}
  iam:
    role: 
      statements:
        - Effect: Allow
          Action:
            - dynamodb:BatchGetItem
            - dynamodb:ConditionCheckItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:GetItem
          Resource:
            - Fn::GetAtt: [RolTable, Arn]
            - Fn::Join:
                - ""
                - [Fn::GetAtt: [RolTable, Arn], "/index/*"]
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:DeleteObject
          Resource: arn:aws:s3:::bucket-serverless-github-challenge/*

# plugins:
#   - serverless-dynamodb
#   - serverless-offline

package:
  individually: true
  exclude:
    - node_modules/**
    - nodejs/**
    - nodejs.zip
  patterns:
    - "!*/**"

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000  # Puerto donde correrá DynamoDB Local
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
  esbuild:
    bundle: true
    minify: true
    sourcemap: true
    target: 'node20'
    format: 'esm'
  cors:
    origin: '*'
    headers:
      - Content-Type
      - Authorization
    allowCredentials: false

functions:
  authorize:
    handler: src/authoraizer/authorize.handler
    layers:
        - { Ref: BaseLambdaLayer }
  login:
      handler: src/auth/lambda/login.handler
      layers:
      - { Ref: BaseLambdaLayer }
      environment:
        ROL_TABLE: { Ref: RolTable }
      events:
        - http:
            path: /auth/login
            method: post
  register:
      handler: src/auth/lambda/register.handler
      layers:
      - { Ref: BaseLambdaLayer }
      environment:
        ROL_TABLE: { Ref: RolTable }
      events:
        - http:
            path: /auth/register
            method: post
  renew:
      handler: src/auth/lambda/renew.handler
      layers:
      - { Ref: BaseLambdaLayer }
      environment:
        ROL_TABLE: { Ref: RolTable }
      events:
        - http:
            authorizer:
              name: authorize
              resultTtlInSeconds: 15
            path: /auth/renew
            method: get
  rolcreate:
    handler: src/rol/lambda/create.handler
    environment:
      ROL_TABLE: { Ref: RolTable }
    events:
      - http:
          authorizer:
            name: authorize
            resultTtlInSeconds: 15
          path: /rol/create
          method: post
  rolget:
    handler: src/rol/lambda/get.handler
    environment:
      ROL_TABLE: 
        Ref: RolTable
    events:
      - http:
          authorizer:
            name: authorize
            resultTtlInSeconds: 15
          path: /rol
          method: get
  rolgetbyid:
    handler: src/rol/lambda/getById.handler
    environment:
      ROL_TABLE: 
        Ref: RolTable
    events:
      - http:
          authorizer:
            name: authorize
            resultTtlInSeconds: 15
          path: /rol/{name}
          method: get
  rolupdate:
    handler: src/rol/lambda/update.handler
    environment:
      ROL_TABLE: 
        Ref: RolTable
    events:
      - http:
          authorizer:
            name: authorize
            resultTtlInSeconds: 15
          path: /rol/update/{name}
          method: put
  roldelete:
    handler: src/rol/lambda/delete.handler
    environment:
      ROL_TABLE: 
        Ref: RolTable
    events:
      - http:
          authorizer:
            name: authorize
            resultTtlInSeconds: 15
          path: /rol/delete/{name}
          method: delete
  usercreate:
    handler: src/user/lambda/create.handler
    layers:
      - { Ref: BaseLambdaLayer }
    environment:
      ROL_TABLE: { Ref: RolTable }
    events:
      - http:
          authorizer:
            name: authorize
            resultTtlInSeconds: 15
          path: /user/create
          method: post
  userget:
    handler: src/user/lambda/get.handler
    environment:
      ROL_TABLE: 
        Ref: RolTable
    events:
      - http:
          path: /user
          authorizer:
            name: authorize
            resultTtlInSeconds: 15
          method: get
  usergetbyid:
    handler: src/user/lambda/getById.handler
    environment:
      ROL_TABLE: 
        Ref: RolTable
    events:
      - http:
          authorizer:
            name: authorize
            resultTtlInSeconds: 15
          path: /user/{id}
          method: get
  userdelete:
    handler: src/user/lambda/delete.handler
    environment:
      ROL_TABLE: 
        Ref: RolTable
    events:
      - http:
          authorizer:
            name: authorize
            resultTtlInSeconds: 15
          path: /user/delete/{id}
          method: delete
  photourl:
    handler: src/photo/lambda/urlPhoto.handler
    layers:
      - { Ref: BaseLambdaLayer }
    environment:
      ROL_TABLE: 
        Ref: RolTable
    events:
      - http:
          authorizer:
            name: authorize
            resultTtlInSeconds: 15
          path: /photo/url
          method: get
  photopost:
    handler: src/photo/lambda/create.handler
    layers:
      - { Ref: BaseLambdaLayer }
    environment:
      ROL_TABLE: 
        Ref: RolTable
    events:
      - s3:
          bucket: bucket-serverless-github-challenge
          event: s3:ObjectCreated:*
          existing: true
  photoget:
    handler: src/photo/lambda/getId.handler
    layers:
      - { Ref: BaseLambdaLayer }
    environment:
      ROL_TABLE: 
        Ref: RolTable
    events:
      - http:
          authorizer:
            name: authorize
            resultTtlInSeconds: 15
          path: /photo
          method: get
  photogetall:
    handler: src/photo/lambda/getAll.handler
    layers:
      - { Ref: BaseLambdaLayer }
    environment:
      ROL_TABLE: 
        Ref: RolTable
    events:
      - http:
          authorizer:
            name: authorize
            resultTtlInSeconds: 15
          path: /photo/all
          method: get
  photogetbyid:
    handler: src/photo/lambda/getById.handler
    layers:
      - { Ref: BaseLambdaLayer }
    environment:
      ROL_TABLE: 
        Ref: RolTable
    events:
      - http:
          authorizer:
            name: authorize
            resultTtlInSeconds: 15
          path: /photo/{photoid}
          method: get
  photodelete:
    handler: src/photo/lambda/delete.handler
    layers:
      - { Ref: BaseLambdaLayer }
    environment:
      ROL_TABLE: 
        Ref: RolTable
    events:
      - http:
          authorizer:
            name: authorize
            resultTtlInSeconds: 15
          path: /photo/delete/{userid}
          method: delete
  phototransform:
    handler: src/photo/lambda/transformations.handler
    layers:
      - { Ref: BaseLambdaLayer }
    environment:
      ROL_TABLE: 
        Ref: RolTable
    events:
      - http:
          authorizer:
            name: authorize
            resultTtlInSeconds: 15
          path: /photo/transform/{photoid}
          method: post

layers:
  base: 
    path: "dependecies-aws"
    name: "BaseLambdaLayer"
    description: "Dependecies for photo"
    compatibleRuntimes:
      - "nodejs20.x"
    compatibleArchitectures:
      - "x86_64"
    package:
      artifact: nodejs.zip

resources:
  Resources:
    RolTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: Rol
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
          - AttributeName: sk
            AttributeType: S
          - AttributeName: gsi1pk
            AttributeType: S
          - AttributeName: gsi1sk
            AttributeType: S
          - AttributeName: gsi2pk
            AttributeType: S
          - AttributeName: gsi2sk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
          - AttributeName: sk
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: GSI1
            KeySchema:
              - AttributeName: gsi1pk
                KeyType: HASH
              - AttributeName: gsi1sk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
          - IndexName: GSI2
            KeySchema:
              - AttributeName: gsi2pk
                KeyType: HASH
              - AttributeName: gsi2sk
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    S3Bucket:
      Type: 'AWS::S3::Bucket'
      Properties:
        BucketName: bucket-serverless-github-challenge
        PublicAccessBlockConfiguration:
          BlockPublicAcls: false
          BlockPublicPolicy: false
          IgnorePublicAcls: false
          RestrictPublicBuckets: false
    S3BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: 
          Ref: S3Bucket
        PolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal: '*'
              Action: 's3:GetObject'
              Resource:
                Fn::Join:
                  - ''
                  - - 'arn:aws:s3:::'
                    - Ref: S3Bucket
                    - /*
